CFLAGS=-Wall -g
all: exercise_10 exercise_10_ifelse exercise_10_nocaps

#exercise_01
#exercise_03
#exercise_07
#exercise_08
#exercise_09

clean:
	rm -f exercise_10 exercise_10_ifelse exercise_10_nocaps

#rm -f exercise_09
#rm -f exercise_01
#rm -f exercise_03
#rm -f exercise_07
#rm -f exercise_08
#rm -f exercise_09
